import { AppData, PotentialIncome, PotentialExpense, Income, Expense, PersonalMovement, MoneySource, MoneyLocation } from '../types';

const getNextDate = (currentDate: Date, frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'): Date => {
    const next = new Date(currentDate);
    switch (frequency) {
        case 'weekly':
            next.setDate(next.getDate() + 7);
            break;
        case 'monthly':
            next.setMonth(next.getMonth() + 1);
            break;
        case 'quarterly':
            next.setMonth(next.getMonth() + 3);
            break;
        case 'yearly':
            next.setFullYear(next.getFullYear() + 1);
            break;
    }
    return next;
};


export const runRecurringTransactionsAutomation = (data: AppData): { updatedData: AppData; hasChanged: boolean } => {
    const today = new Date();
    today.setHours(23, 59, 59, 999); // Ensure we include all of today

    let hasChanged = false;
    const newIncomes: Income[] = [];
    const newExpenses: Expense[] = [];
    const newPersonalMovements: PersonalMovement[] = [];

    const updatedPotentialIncomes = data.potentialIncomes.map(pi => {
        if (pi.frequency === 'one-off' || !pi.startDate) return pi;

        let lastDate = pi.lastGeneratedDate ? new Date(pi.lastGeneratedDate) : new Date(pi.startDate);
        let nextDueDate = new Date(lastDate);

        // If it hasn't been generated yet, the next due date is the start date
        if (!pi.lastGeneratedDate) {
            nextDueDate = new Date(pi.startDate);
        } else {
             // Otherwise, calculate the next one from the last generated
            nextDueDate = getNextDate(lastDate, pi.frequency);
        }
       
        while (nextDueDate <= today) {
            // Check if it exceeds the end date
            if (pi.endDate && nextDueDate > new Date(pi.endDate)) {
                break;
            }

            hasChanged = true;

            if (pi.source === MoneySource.AUTONOMO) {
                const newIncome: Income = {
                    id: `inc-auto-${Date.now()}-${Math.random()}`,
                    date: nextDueDate.toISOString(),
                    isPaid: false,
                    concept: pi.concept,
                    clientName: 'Ingreso Recurrente',
                    invoiceNumber: '', // User to fill this
                    baseAmount: pi.baseAmount || 0,
                    vatRate: pi.vatRate || 0,
                    irpfRate: pi.irpfRate || 0,
                    source: pi.source,
                    location: pi.location,
                    autoGenerated: true,
                };
                newIncomes.push(newIncome);
            } else { // Personal Income
                 const newMovement: PersonalMovement = {
                    id: `pm-auto-${Date.now()}-${Math.random()}`,
                    date: nextDueDate.toISOString(),
                    isPaid: false,
                    concept: pi.concept,
                    amount: pi.amount || 0,
                    type: 'income',
                    categoryId: '', // User should categorize
                    location: pi.location,
                    autoGenerated: true,
                };
                newPersonalMovements.push(newMovement);
            }
            
            lastDate = new Date(nextDueDate);
            nextDueDate = getNextDate(nextDueDate, pi.frequency);
        }

        return { ...pi, lastGeneratedDate: lastDate.toISOString() };
    });
    
    const updatedPotentialExpenses = data.potentialExpenses.map(pe => {
        if (pe.frequency === 'one-off' || !pe.startDate) return pe;

        let lastDate = pe.lastGeneratedDate ? new Date(pe.lastGeneratedDate) : new Date(pe.startDate);
        let nextDueDate = new Date(lastDate);

        if (!pe.lastGeneratedDate) {
            nextDueDate = new Date(pe.startDate);
        } else {
            nextDueDate = getNextDate(lastDate, pe.frequency);
        }

        while (nextDueDate <= today) {
             if (pe.endDate && nextDueDate > new Date(pe.endDate)) {
                break;
            }
            hasChanged = true;

            const newMovement: PersonalMovement = {
                id: `pm-auto-${Date.now()}-${Math.random()}`,
                date: nextDueDate.toISOString(),
                isPaid: false,
                concept: pe.concept,
                amount: pe.amount,
                type: 'expense',
                categoryId: pe.categoryId,
                location: MoneyLocation.PERS_BANK, // Default, user can change
                autoGenerated: true,
            };
            newPersonalMovements.push(newMovement);
            
            lastDate = new Date(nextDueDate);
            nextDueDate = getNextDate(nextDueDate, pe.frequency);
        }
        
        return { ...pe, lastGeneratedDate: lastDate.toISOString() };
    });


    if (!hasChanged) {
        return { updatedData: data, hasChanged: false };
    }

    const updatedData: AppData = {
        ...data,
        incomes: [...data.incomes, ...newIncomes],
        expenses: [...data.expenses, ...newExpenses],
        personalMovements: [...data.personalMovements, ...newPersonalMovements],
        potentialIncomes: updatedPotentialIncomes,
        potentialExpenses: updatedPotentialExpenses,
    };

    return { updatedData, hasChanged: true };
};