import { AppData, ScheduledTransaction, Income, Expense, PersonalMovement, MoneyLocation, MoneySource } from '../types';

const getNextDate = (currentDate: Date, frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'): Date => {
    const next = new Date(currentDate);
    switch (frequency) {
        case 'weekly':
            next.setDate(next.getDate() + 7);
            break;
        case 'monthly':
            next.setMonth(next.getMonth() + 1);
            break;
        case 'quarterly':
            next.setMonth(next.getMonth() + 3);
            break;
        case 'yearly':
            next.setFullYear(next.getFullYear() + 1);
            break;
    }
    return next;
};

export const runRecurringTransactionsAutomation = (data: AppData): { updatedData: AppData; hasChanged: boolean } => {
    const today = new Date();
    today.setHours(23, 59, 59, 999); // Ensure we include all of today

    let hasChanged = false;
    const newIncomes: Income[] = [];
    const newExpenses: Expense[] = [];
    const newPersonalMovements: PersonalMovement[] = [];

    const updatedScheduledTransactions = data.scheduledTransactions.map(st => {
        if (st.frequency === 'one-off' || !st.startDate) return st;

        let lastDate = st.lastGeneratedDate ? new Date(st.lastGeneratedDate) : new Date(st.startDate);
        let nextDueDate = new Date(lastDate);

        // If it hasn't been generated yet, the next due date is the start date
        if (!st.lastGeneratedDate) {
            nextDueDate = new Date(st.startDate);
        } else {
             // Otherwise, calculate the next one from the last generated
            nextDueDate = getNextDate(lastDate, st.frequency);
        }
       
        while (nextDueDate <= today) {
            // Check if it exceeds the end date
            if (st.endDate && nextDueDate > new Date(st.endDate)) {
                break;
            }

            hasChanged = true;

            if (st.scope === 'professional') {
                if (st.type === 'income') {
                    const newIncome: Income = {
                        id: `inc-auto-${Date.now()}-${Math.random()}`,
                        invoiceNumber: '',
                        date: nextDueDate.toISOString(),
                        clientName: st.concept,
                        concept: st.concept,
                        baseAmount: st.baseAmount || 0,
                        vatRate: st.vatRate || 0,
                        irpfRate: st.irpfRate || 0,
                        // FIX: Use MoneySource enum member for type safety
                        source: MoneySource.AUTONOMO,
                        isPaid: false,
                        location: st.location || MoneyLocation.PRO_BANK,
                        autoGenerated: true,
                    };
                    newIncomes.push(newIncome);
                } else { // Professional Expense
                     const newExpense: Expense = {
                        id: `exp-auto-${Date.now()}-${Math.random()}`,
                        date: nextDueDate.toISOString(),
                        isPaid: false,
                        providerName: st.concept,
                        concept: st.concept,
                        baseAmount: st.baseAmount || 0,
                        vatRate: st.vatRate || 0,
                        categoryId: '', // User to categorize
                        location: st.location || MoneyLocation.PRO_BANK,
                        isDeductible: true,
                        autoGenerated: true,
                    };
                    newExpenses.push(newExpense);
                }
            } else { // Personal Movement
                 const newMovement: PersonalMovement = {
                    id: `pm-auto-${Date.now()}-${Math.random()}`,
                    date: nextDueDate.toISOString(),
                    isPaid: false,
                    concept: st.concept,
                    amount: st.amount || 0,
                    type: st.type,
                    categoryId: st.categoryId || '', // User to categorize if missing
                    location: st.location || MoneyLocation.PERS_BANK,
                    autoGenerated: true,
                };
                newPersonalMovements.push(newMovement);
            }
            
            lastDate = new Date(nextDueDate);
            nextDueDate = getNextDate(nextDueDate, st.frequency);
        }

        return { ...st, lastGeneratedDate: lastDate.toISOString() };
    });
    
    if (!hasChanged) {
        return { updatedData: data, hasChanged: false };
    }

    const updatedData: AppData = {
        ...data,
        incomes: [...data.incomes, ...newIncomes],
        expenses: [...data.expenses, ...newExpenses],
        personalMovements: [...data.personalMovements, ...newPersonalMovements],
        scheduledTransactions: updatedScheduledTransactions,
    };

    return { updatedData, hasChanged: true };
};